In [1]:
import os
import platform
import sys
import ipywidgets as widgets
from IPython.display import display
from IPython.core.debugger import set_trace
 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
 
import tensorflow as tf
from tensorflow import keras
import tensorflow.keras.layers as L
import tensorflow.keras.backend as K
import tensorflow_probability as tfp
from tqdm import tqdm
%matplotlib inline
 
print("OS Type: %s" % os.name)
print("OS Name: %s" % platform.system())
print("OS Release: %s" % platform.release())
print(f'Using Python={sys.version}')
print(f'Using Tensorflow={tf.__version__}')
print(f'Using Keras={keras.__version__}')
print("GPU Available: ", tf.test.is_gpu_available())


/home/alan/projects/venv-jupyter/lib/python3.7/site-packages/pandas/compat/__init__.py:84: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


OS Type: posix
OS Name: Linux
OS Release: 4.15.0-50-generic
Using Python=3.7.2 (default, Mar 30 2019, 15:56:42) 
[GCC 5.4.0 20160609]
Using Tensorflow=2.0.0-rc2
Using Keras=2.2.4-tf
GPU Available:  True


In [10]:
%load_ext autoreload
%autoreload 2

In [17]:
%%writefile image_augmentation.py
import os
import numpy as np
import pandas as pd
import cv2
 
import tensorflow as tf
from tensorflow.keras import preprocessing as preproc

def load_raw_image(filename):
    return cv2.imread(filename)

def apply_augmentations(zoom, bright, shift, shear, rotate):
    

Overwriting image_augmentation.py


In [18]:
from image_augmentation import *

In [20]:
from load_and_preprocess_data import *
train_info = collect_filename_mapping('train_imgs')

load_image(train_info.filename_map['Russia'][0]).shape

train_imgs/Russia/Alexandrov_008.jpg
[[[122  82  24]
  [122  82  24]
  [122  82  24]
  ...
  [ 53  56  60]
  [ 49  52  56]
  [ 49  52  56]]

 [[122  82  24]
  [122  82  24]
  [122  82  24]
  ...
  [ 51  54  58]
  [ 45  48  52]
  [ 45  48  52]]

 [[122  82  24]
  [122  82  24]
  [122  82  24]
  ...
  [ 46  48  49]
  [ 38  40  41]
  [ 38  40  41]]

 ...

 [[122  93  66]
  [122  93  66]
  [122  93  66]
  ...
  [120  96  78]
  [120  96  78]
  [120  96  78]]

 [[122  93  66]
  [122  93  66]
  [122  93  66]
  ...
  [120  96  78]
  [120  96  78]
  [120  96  78]]

 [[122  93  66]
  [122  93  66]
  [122  93  66]
  ...
  [120  96  78]
  [120  96  78]
  [120  96  78]]]


AttributeError: 'NoneType' object has no attribute 'shape'